python3 extract_rule.py   concept_athletehomestadium &
python3 extract_rule.py  concept_athleteplaysforteam &
python3 extract_rule.py  concept_athleteplaysinleague &
python3 extract_rule.py  concept_athleteplayssport &
python3 extract_rule.py  concept_organizationhiredperson &
python3 extract_rule.py concept_personborninlocation &
python3 extract_rule.py concept_personleadsorganization &
python3 extract_rule.py concept_teamplaysinleague &
python3 extract_rule.py concept_teamplayssport &
python3 extract_rule.py concept_worksfor &
